@base-url = http://localhost:8081
@email-1 = chris@example.com
@email-2 = bootsie@test.com
@tweet-id = 05f3e895-0185-4338-88d3-25674522ad73
@boots-username = bootsie
@chris-username = unchartedzone


# @name Login
POST http://localhost:8081/login
Content-Type: application/json

{
  "user": {
    "email": "{{email-1}}",
    "password": "password123"
  }
}
> {%
    client.global.set("auth_token", response.body.data.attributes.accessToken);
%}

###

# @name FetchMyself
GET {{base-url}}/me
Authorization: Bearer {{auth_token}}

###

# @name FetchUserByUsername
GET {{base-url}}/users/bootsie
Authorization: Bearer {{auth_token}}

###

# @name UpdateUser
PATCH {{base-url}}/users/e296bfe6-89b6-4acb-ab29-be5c0fcf40bb
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="user"
Content-Type: application/json

{
"user": {
  "name": "Bobby Light"
}
}
--WebAppBoundary--

###

# @name UpdateImage
PATCH {{base-url}}/users/update-image
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="field"
Content-Type: text/plain

banner_image
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="bootsie.jpg"
Content-Type: image/jpeg

< ../../../../Pictures/bootsie/bootsie.jpg

--WebAppBoundary--

###

# @name CreateTweet
POST {{base-url}}/tweets
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "tweet": {
    "text": "Meowwww"
  }
}

###

# @name LikeTweet
POST {{base-url}}/tweets/{{tweet-id}}/like
Authorization: Bearer {{auth_token}}

###

# @name UnlikeTweet
POST {{base-url}}/tweets/{{tweet-id}}/unlike
Authorization: Bearer {{auth_token}}

###

# @name FetchTweets
GET {{base-url}}/tweets
Authorization: Bearer {{auth_token}}

###

# @name FetchOwnProfileTweets
GET {{base-url}}/tweets/profile/{{chris-username}}/protected
Authorization: Bearer {{auth_token}}

###

# @name FetchProfileTweets
GET {{base-url}}/tweets/profile/{{chris-username}}

###

# @name FetchSingleTweet
GET {{base-url}}/tweets/{{tweet-id}}

###

# @name FetchLikedTweets
GET {{base-url}}/tweets/liked
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name RetweetTweet
POST {{base-url}}/tweets/{{tweet-id}}/retweet
Authorization: Bearer {{auth_token}}

###

# @name UndoRetweet
POST {{base-url}}/tweets/{{tweet-id}}/unretweet
Authorization: Bearer {{auth_token}}

###