export const iconVariants = [
  "balloon",
  "bell",
  "bell-outline",
  "bird",
  "bookmark",
  "bookmark-outline",
  "calendar",
  "camera-outline",
  "chain",
  "cross",
  "ellipsis",
  "feather",
  "heart",
  "heart-outline",
  "home",
  "home-outline",
  "left-arrow",
  "list",
  "location",
  "magnifying-glass",
  "magnifying-glass-bold",
  "message",
  "more",
  "person",
  "person-outline",
  "picture",
  "profile",
  "profile-outline",
  "pound",
  "reply",
  "retweet",
  "share",
] as const;

export type IconVariant = (typeof iconVariants)[number];
