export const iconVariants = [
  "balloon",
  "bell",
  "bell-outline",
  "bird",
  "bookmark",
  "bookmark-outline",
  "broken-heart",
  "calendar",
  "camera-outline",
  "chain",
  "chevron-right",
  "cross",
  "download",
  "ellipsis",
  "feather",
  "gear",
  "gif",
  "heart",
  "heart-outline",
  "home",
  "home-outline",
  "key",
  "left-arrow",
  "list",
  "list-outline",
  "location",
  "magnifying-glass",
  "magnifying-glass-bold",
  "message",
  "more",
  "person",
  "person-outline",
  "picture",
  "profile",
  "profile-follow",
  "profile-outline",
  "pound",
  "reply",
  "retweet",
  "share",
  "smiley",
] as const;

export type IconVariant = (typeof iconVariants)[number];
