# Use the official Node.js version 22 image
FROM node:22-alpine

# Set environment variables

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock first for caching dependencies
COPY ./package.json ./

COPY ./yarn.lock ./

RUN ls -la 

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the default Vue.js development server port
EXPOSE 8080

# Start the development server with Yarn
CMD ["yarn", "dev", "--host", "0.0.0.0"]
