@base-url=http://localhost:8081
@my-user-id=e296bfe6-89b6-4acb-ab29-be5c0fcf40bb
@user-1 = "chris@example.com"
@user-2 = "bootsie@test.com"

# @name login
POST {{base-url}}/login
Content-Type: application/json

{
  "user": {
    "email": {{user-1}},
    "password": "password123"
  }
}
###

# @name signup
POST {{base-url}}/signup
Content-Type: application/json

{
  "user": {
    "username": "bootsie",
    "email": "bootsie@test.com",
    "password": "password123",
    "name": "Bootsie Valdez",
    "dateOfBirth": "8/17/2015"
  }
}

###

# @name refreshUser
POST {{base-url}}/refresh
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImNocmlzQHRlc3QuY29tIiwiZXhwIjoxNjg3Mzg4NDczfQ.HK84ePZ16YksRXNoSFsOJtz0WYMmJ8HNp88l9uDCEng; path=/; expires=Wed, 21 Jun 2023 23:01:13 GMT; secure; HttpOnly; SameSite=Lax

###

# @name fetchMe
GET {{base-url}}/me
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

###

# @name fetchUser
GET {{base-url}}/users/{{my-user-id}}
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

### 

# @name updateMyself
PATCH {{base-url}}/users/{{login.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}
Content-Type: application/json

{
  "user": {
    "dateOfBirth": "17-10-2015"
  }
}
### 

# @name fetchTweets
GET {{base-url}}/tweets
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

###


# @name createMedia
POST {{base-url}}/media

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ../../
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# @name createTweet
POST {{base-url}}/tweets
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "tweet": {
    "text": "another tweet!"
  }
}
###

# @name LikeTweet
POST {{base-url}}/tweets/e485b8f5-6b3f-4572-bd46-5f5a470d611f/like
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

###