@base-url=http://localhost:8081
@my-user-id=e296bfe6-89b6-4acb-ab29-be5c0fcf40bb

# @name login
POST {{base-url}}/login
Content-Type: application/json

{
  "user": {
    "email": "chris@example.com",
    "password": "password123"
  }
}
###

# @name signup
POST {{base-url}}/signup
Content-Type: application/json

{
  "user": {
    "username": "unchartedzone",
    "email": "chris@test.com",
    "password": "password123",
    "name": "Christian Valdez"
  }
}

###

# @name refreshUser
POST {{base-url}}/refresh
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImNocmlzQHRlc3QuY29tIiwiZXhwIjoxNjg3Mzg4NDczfQ.HK84ePZ16YksRXNoSFsOJtz0WYMmJ8HNp88l9uDCEng; path=/; expires=Wed, 21 Jun 2023 23:01:13 GMT; secure; HttpOnly; SameSite=Lax

###

# @name fetchMe
GET {{base-url}}/me
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

###

# @name fetchUser
GET {{base-url}}/users/{{my-user-id}}
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}

### 

# @name updateMe
PATCH {{base-url}}/users/{{my-user-id}}
Authorization: Bearer {{login.response.body.data.attributes.accessToken}}
Content-Type: application/json

{
  "user": {
    "name": "Christian Valdez"
  }
}
### 

# @name fetchTweets
GET {{base-url}}/tweets
Authorization: Bearer {{login.response.body.access_token}}

###

# @name createTweet
POST {{base-url}}/tweets
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "tweet": {
    "text": "another tweet!"
  }
}
###